name: black-action
on:
  pull_request:
jobs:
  linter_name:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Super-linter
        uses: super-linter/super-linter@v6.0.0  # x-release-please-version
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true
