name: black-action
on:
  pull_request:
jobs:
  linter_name:
    name: Black Formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: datadog/action-py-black-formatter@v2.4
        with:
          check_mode: "true"
