name: SuperLinter
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  linter_name:
    name: Super-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Super-linter
        uses: super-linter/super-linter/slim@v6.0.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_ALL_CODEBASE: false
